# Generated by Django 4.2.1 on 2023-08-30 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appservicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='imagen',
            field=models.ImageField(upload_to='media'),
        ),
    ]
